"""empty message

Revision ID: e23dcbc0b17f
Revises: 
Create Date: 2018-12-02 21:05:08.216913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23dcbc0b17f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'worker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('worker', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
